[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rest-api"
version = "0.1.0"
description = "REST API for managing contacts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "fastapi>=0.136.3",
    "sqlalchemy>=2.0.50",
    "psycopg2-binary>=2.9.10",
    "asyncpg>=0.28.0",
    "pydantic[email]>=2.0",
    "pydantic-settings>=2.0",
    "uvicorn>=0.32.0",
    "python-dotenv>=1.0.0",
    "python-jose[cryptography]>=3.5.0",
    "passlib[bcrypt]>=1.7.4",
    "cloudinary>=1.44.2",
    "slowapi>=0.1.10",
    "httpx>=0.28.0",
    "fastapi-mail>=1.6.5",
    "python-multipart>=0.0.32",
]
